name: 'build' 
on: # rebuild any PRs and main branch changes
  push:
    tags:
      - 'v**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/whynotea/devcontainer-wails
          imageTag: latest,${{github.ref_name}}
          cacheFrom: ghcr.io/whynotea/devcontainer-wails
          push: always
